# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
references:
  defaults: &defaults
    working_directory: ~/project
    docker:
      - image: circleci/node:8-browsers

  cache_key: &cache_key
    todo-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}

  attach_workspace: &attach_workspace
    attach_workspace:
      at: ~/

version: 2
jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore cache
          key: *cache_key
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          name: Save cache
          key: *cache_key
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/
          paths:
            - project
            - .ssh
  lint:
    <<: *defaults
    steps:
      - *attach_workspace
      - run:
          name: Run ESLint
          command: yarn lint:js

  test_1:
    <<: *defaults
    steps:
      - *attach_workspace
      - run:
          name: Run first half of split tests
          command: yarn exam --split=2 --partition=1 --parallel

  test_2:
    <<: *defaults
    steps:
      - *attach_workspace
      - run:
          name: Run first half of split tests
          command: yarn exam --split=2 --partition=2 --parallel

workflows:
  version: 2
  default:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test_1:
          requires:
            - install
      - test_2:
          requires:
            - install
